scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: 'supabase'
    scrape_interval: 60s
    metrics_path: /customer/v1/privileged/metrics
    scheme: https
    basic_auth:
      username: username
      password: change-this-password
    static_configs:
      - targets:
          - 'mljqvfqtpargrwxifxum.supabase.co:443'
        labels:
          project: 'transcendence'