{
 "title": "Transcendence",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Matches Played",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transcendence_matches_played_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Active Games",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "transcendence_active_games", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Games Completed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transcendence_games_completed_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Games Started",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transcendence_games_started_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}